import type { Metadata } from 'next';
import '@repo/design-system/styles/globals.css';
import { Providers } from '@repo/auth/provider';
import { primaryFont } from '@repo/design-system/lib/fonts';
import QueryProvider from '@/src/providers/QueryProvider';
import {
  getMessages,
  NextIntlClientProvider,
} from '@repo/internationalization/src/NextIntlClientProvider';
import { routing } from '@repo/internationalization/src/i18n/routing';
import { setRequestLocale } from 'next-intl/server';
import { Toolbar } from '@repo/cms/components/toolbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html lang='en'>
      <body className={`${primaryFont.className} antialiased`}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <QueryProvider>
            <Providers>{children}</Providers>
          </QueryProvider>
        </NextIntlClientProvider>
        <Toolbar />
      </body>
    </html>
  );
}
