import type { Metadata } from 'next';
import '@repo/design-system/styles/globals.css';
import { Providers } from '@repo/auth/provider';
import { primaryFont } from '@repo/design-system/lib/fonts';
import QueryProvider from '@/src/providers/QueryProvider';
import { Toolbar } from '@repo/cms/components/toolbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${primaryFont.className} antialiased`}>
        <QueryProvider>
          <Providers>{children}</Providers>
        </QueryProvider>
        <Toolbar />
      </body>
    </html>
  );
}
